##################################
#                                #
#         RESTART ENTRIES        #
#                                #
##################################

settings:
  # หมายเหตุ: เข้าชมวิกิเพื่อดูข้อมูลเพิ่มเติมเกี่ยวกับประเภทคำสั่งทั้งหมด
  # หมายเหตุ: ประเภทคำสั่งที่มีให้ใช้งานสำหรับ restartCommands -> normal, time, proxy, proxydelay
  # หมายเหตุ: วันที่ใช้งานได้สำหรับคำสั่งเฉพาะวัน -> [MONDAY], [TUESDAY], [WEDNESDAY], [THURSDAY], [FRIDAY], [SATURDAY], [SUNDAY] **ข้อควรระวัง** แท็กวันต้องอยู่หลังประเภทคำสั่ง (ยกเว้น normal)
  restartCommands:
    #- '[proxy:5] คำสั่งที่จะรันผ่านพร็อกซี 5 วินาทีก่อนรีสตาร์ท'
    #- '[time:15] คำสั่งที่จะรัน 15 วินาทีก่อนรีสตาร์ท'
    #- '[proxydelay:30] คำสั่งที่จะถูกกำหนดเวลาบนพร็อกซีและรันใน 30 วินาที คำสั่ง PROXYDELAY จะทำงานเมื่อตัวนับเวลาถอยหลังรีสตาร์ทเหลือ 0'
    #- '[proxydelay:15] alert เซิร์ฟเวอร์เปิดให้บริการแล้ว เข้ามาเล่นกันเลย!'
    #- '[time:10] [MONDAY] คำสั่งที่จะรัน 10 วินาทีก่อนรีสตาร์ทและเฉพาะวันจันทร์เท่านั้น'
    #- '[FRIDAY] คำสั่งที่จะรันขณะรีสตาร์ทและเฉพาะวันศุกร์เท่านั้น'
    #- '[proxy] test (ทดสอบคำสั่งผ่านพร็อกซี)'
    - "save-all"
    - "restart"

  # หมายเหตุ: เข้าชมวิกิเพื่อดูข้อมูลเพิ่มเติมเกี่ยวกับประเภทคำสั่งทั้งหมด
  # หมายเหตุ: ประเภทคำสั่งที่มีให้ใช้งานสำหรับ restartCommands -> time, proxy
  # หมายเหตุ: วันที่ใช้งานได้สำหรับคำสั่งเฉพาะวัน -> [MONDAY], [TUESDAY], [WEDNESDAY], [THURSDAY], [FRIDAY], [SATURDAY], [SUNDAY]
  commandsAfterReboot:
  #- '[proxy:30] คำสั่งที่จะรันผ่าน Bungee 30 วินาทีหลังเซิร์ฟเวอร์เปิดทำงาน'
  #- '[time:15] [WEDNESDAY] broadcast วันนี้วันพุธแล้วนะทุกคน!'

  # หมายเหตุ: หากต้องการรีสตาร์ทสองครั้งในวันเดียวกัน ให้เพิ่มรายการใหม่ด้วยชื่อวันเดิมแต่ระบุเวลาต่างกัน
  # หมายเหตุ: ช่วงเวลาที่ถูกต้อง -> วันจันทร์-อาทิตย์ (ภาษาอังกฤษ) และรูปแบบเวลา 00;00 ถึง 24;00
  # หมายเหตุ: คุณยังสามารถใช้ "Daily" แทนชื่อวันเฉพาะเจาะจงเพื่อรีสตาร์ททุกวันตามเวลาที่กำหนด เช่น "Daily;05;00" จะรีสตาร์ททุกวันเวลาตี 5
  restarts:
    - "Monday;00;00"
    - "Monday;12;00"
    - "Tuesday;00;00"
    - "Tuesday;12;00"
    - "Wednesday;00;00"
    - "Wednesday;12;00"
    - "Thursday;00;00"
    - "Thursday;12;00"
    - "Friday;00;00"
    - "Friday;12;00"
    - "Saturday;00;00"
    - "Saturday;12;00"
    - "Sunday;00;00"
    - "Sunday;12;00"
  #- 'Daily;00;00'

  # หมายเหตุ: ตั้งค่าข้อความแจ้งเตือนในไฟล์ messages.yml ของ UltimateAutoRestart!
  messageAtIntervals:
    - "1800"
    - "600"
    - "60"
    - "30"
    - "3"
    - "2"
    - "1"

  # หมายเหตุ: ตั้งค่าเสียงแจ้งเตือนในไฟล์ sounds.yml ของ UltimateAutoRestart!
  soundAtIntervals:
    - "1800"
    - "600"
    - "60"
    - "30"
    - "3"
    - "2"
    - "1"

  # หมายเหตุ: ข้อความนี้จะแสดงขึ้นมาเมื่อตัวจับเวลารีสตาร์ทไม่ได้ทำงาน!
  unscheduledIntervalValue: "&f&lN/A"

##################################
#                                #
#         RESTART DELAY          #
#                                #
##################################

# หมายเหตุ: ยืดเวลา (เลื่อน) การรีสตาร์ทออกไปหากมีจำนวนผู้เล่นออนไลน์เกินค่าที่กำหนด!
delayRestart:
  enabled: false
  checkSecondsBeforeRestart: 30
  minimumPlayers: 1
  delayBySeconds: 600

##################################
#                                #
#    VALUE DISPLAY SETTINGS      #
#                                #
##################################

# หมายเหตุ: ตั้งค่ารูปแบบการแสดงผลของช่วงเวลา!
format:
  seconds: "s"
  second: "s"
  minutes: "m "
  minute: "m "
  hours: "h "
  hour: "h "
  days: "D "
  day: "D "
  splitter: "and "
