name: LuminaCore
version: 1.0.0
main: core.luminaworld.LuminaCore
api-version: "1.20"
folia-supported: true
description: ปลั๊กอินควบคุมระบบและส่วนเสริมหลักของเซิร์ฟเวอร์ Luminaris
author: Loma0531

commands:
  luminacore:
    description: คำสั่งจัดการระบบหลักของ LuminaCore
    aliases:
      - luminaris
      - luminaworld
      - llw
      - lc
    permission: luminacore.admin
    usage: /<command> [reload]
